server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

    gateway:
      routes:
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/v1/vehicle/**


        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**







eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
